export { default as About } from "./About";
export { default as Appointments } from "./Appo";
export { default as Contact } from "./Contact";
export { default as Courses } from "./Courses";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as Navigation } from "./Navigation";
export { default as Profile } from "./Profile";
export { default as Stats } from "./Stats";